baseURL = 'https://dvesti.github.io/hinode-books/'
defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true
timeout = "10m"

[params.main]
    canonifyAssetsURLs = true
#    canonifyURLs = true 
[params.style]
    themeFontPreload = "/hinode-books/fonts/inter-v12-latin-regular.woff2"

[pagination]
  PagerSize = 9

[[module.imports]]
    path = 'github.com/gethinode/hinode'

[languages.en]
    title = 'HHB'
    contentDir = 'content/en'
    languageCode = 'en'
    languageName = 'English'
[languages.en.params.sections.blog]
    reference = "More Posts"
[languages.en.params.sections.projects]
    reference = "More Projects"
[languages.en.params.sections.books]
    reference = "More Books"
[languages.en.params.head]
    tagline = "A Hugo Theme"
[languages.en.params.social]
    title = "Follow me"
    caption = "I work on everything coding and tweet developer memes"

[languages.sv]
    title = 'HHB'
    contentDir = 'content/sv'
    languageCode = 'sv'
    languageName = 'Svenska'
[languages.sv.params.sections.blog]
    reference = "Fler inlägg"
[languages.sv.params.sections.projects]
    reference = "Fler projekt"
[languages.sv.params.sections.books]
    reference = "Fler böcker"
[languages.sv.params.head]
    tagline = "Ett Hugo-tema"
[languages.sv.params.social]
    title = "Följ mig"
    caption = "Jag arbetar med allt som har med kodning att göra och twittrar utvecklarmemer"

[languages.ru]
    title = 'HHB'
    contentDir = 'content/ru'
    languageCode = 'ru'
    languageName = 'Русский'
[languages.ru.params.sections.blog]
    title = "Блог"
    sort = "date"
    reverse = true
    cols = 3
    color = "body-tertiary"
    padding = "0"
    orientation = "stacked"
    style = "border-0 card-zoom card-body-margin"
    reference = "Больше..."
[languages.ru.params.sections.projects]
    title = "Проекты"
    footer = "tags"
    nested = true
    cols = 1
    #background = "body-tertiary"
    color = "body-tertiary"
    padding = "3"
    orientation = "horizontal"
    reference = "Больше Проектов"
[languages.ru.params.sections.books]
    title = "Книги"
    color = "body-tertiary"
    reference = "Больше Книг"
[languages.ru.params.head]
    tagline = "A Hugo Theme"
[languages.ru.params.social]
    title = "Подписка"
    caption = "Наши соц. сети:"

[params.navigation]
    logo = "img/logo_icon.svg"
    sidebar = true
    toc = true
    includeToc = true

[params.home]
    sections = ['blog', 'projects', 'books']

[params.sections.books]
    nested = false
    
[params.sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true
    
[[params.sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[params.sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[params.sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[params.sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[params.sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true
    
[[params.sharing.providers]]
    name = "Telegram"
    url = "https://t.me/share/url?url={url}&text={title}"
    icon = "fab telegram"
    weight = 60   
    
[[params.sharing.providers]]
    name = "VK"
    url = "https://vk.com/share.php?url={url}"
    icon = "fab vk"
    weight = 70    
    
[[languages.en.menus.main]]
    name = 'About'
    pageRef = 'about/'
    weight = 10
[[languages.en.menus.main]]
    name = 'Blog'
    pageRef = 'blog/'
    weight = 20
[[languages.en.menus.main]]
    name = 'Projects'
    pageRef = 'projects/'
    weight = 30
[[languages.en.menus.main]]
    name = 'Books'
    pageRef = 'books/'
    weight = 40
[[languages.en.menus.main]]
    name = 'Tags'
    pageRef = 'tags/'
    weight = 50

[[languages.sv.menus.main]]
    name = 'Om'
    pageRef = 'about/'
    weight = 10
[[languages.sv.menus.main]]
    name = 'Blogg'
    pageRef = 'blog/'
    weight = 20
[[languages.sv.menus.main]]
    name = 'Projekt'
    pageRef = 'projects/'
    weight = 30
[[languages.sv.menus.main]]
    name = 'Böcker'
    pageRef = 'books/'
    weight = 40
[[languages.sv.menus.main]]
    name = 'Taggar'
    pageRef = 'tags/'
    weight = 50
    
[[languages.ru.menus.main]]
    name = 'О сайте'
    pageRef = 'about/'
    weight = 10
[[languages.ru.menus.main]]
    name = 'Блог'
    pageRef = 'blog/'
    weight = 20
[[languages.ru.menus.main]]
    name = 'Проекты'
    pageRef = 'projects/'
    weight = 30
[[languages.ru.menus.main]]
    name = 'Книги'
    pageRef = 'books/'
    weight = 40
[[languages.ru.menus.main]]
    name = 'Тэги'
    pageRef = 'tags/'
    weight = 50
    
[[languages.ru.menus.sample]]
    name = 'Блог'
    pageRef = 'blog/'
    weight = 20
[[languages.ru.menus.sample]]
    name = 'Проекты'
    pageRef = 'projects/'
    weight = 30    
    
[[languages.en.menus.social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[languages.en.menus.social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[languages.en.menus.social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30

[[languages.sv.menus.social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[languages.sv.menus.social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[languages.sv.menus.social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30
  
#  [[languages.ru.menus.social]]
#  name = "LinkedIn"
#  pre = "fab linkedin"
#  url = "https://linkedin.com/"
#  weight = 10

#[[languages.ru.menus.social]]
#  name = "GitHub"
#  pre = "fab fa-github"
#  url = "https://github.com/"
#  weight = 20

#[[languages.ru.menus.social]]
#  name = "Medium"
#  pre = "fab medium"
#  url = "https://medium.com/"
#  weight = 30

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/dvesti"
  weight = 10

[[languages.ru.menus.social]]
  name = "Facebook"
  pre = "fab facebook"
  url = "https://facebook.com/vladimir.dmitrijev.9"
  weight = 20
  
[[languages.ru.menus.social]]
  name = "Blogger"
  pre = "fab blogger"
  url = "https://estonija.blogspot.com"
  weight = 30 
  clipboard = true

[[languages.ru.menus.social]]
  name = "Flickr"
  pre = "fab flickr"
  url = "https://www.flickr.com/photos/190444282@N04/"
  weight = 40
  
[[languages.ru.menus.social]]
  name = "Telegram"
  pre = "fab telegram"
  url = "https://t.me/estonija"
  weight = 50  
  
[[languages.ru.menus.social]]
  name = "X"
  pre = "fab x-twitter"
  url = "https://x.com/Prorab"
  weight = 60  
  
[[languages.ru.menus.social]]
  name = "VK"
  pre = "fab vk"
  url = "https://vk.com/dmitrijev"
  weight = 70  
  
[[languages.ru.menus.social]]
  name = "Wordpress"
  pre = "fab wordpress"
  url = "https://dvesti.wordpress.com/"
  weight = 80    

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
